version: "3.8"

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    expose:
      - "8000:8000"
    env_file:
      - ./back/.env
    restart: always

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
