version: "3.8"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev    # usa o DEV Dockerfile
    volumes:
      - ./front:/app                # seu código local
      - /app/node_modules           # volume anônimo para preservar os módulos instalados
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true    # opcional: força watch funcionar em WSL/Windows
