services:
  backend:
    build: ./back

    ports:
      - "8000:8000"

    volumes:
      - ./back:/app

    env_file:
      - ./back/.env
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    build: ./front

    ports:
      - "5173:5173"

    volumes:
      - ./front:/app

    depends_on:
      - backend
