services:
  backend:
    build: ./back

    ports:
      - "8000:8000"

    volumes:
      - ./back:/app
      - ./back/planilha-inscritos-e54203243565.json:/app/credentials.json

    env_file:
      - ./back/.env
    environment:
      PYTHONUNBUFFERED: "1"
      ALLOWED_HOSTS: "www.hackathon-ia.coppe.ufrj.br"
      CSRF_TRUSTED_ORIGINS: "https://www.hackathon-ia.coppe.ufrj.br"

  frontend:
    build: ./front

    ports:
      - "5173:5173"

    volumes:
      - ./front:/app

    depends_on:
      - backend

