# Generated by Django 5.2.2 on 2025-06-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(choices=[('EMI', 'Ensino Médio Incompleto'), ('EMC', 'Ensino Médio Completo'), ('GI', 'Graduação Incompleta'), ('GC', 'Graduação Completa'), ('PGI', 'Pós-Graduação Incompleta'), ('PGC', 'Pós-Graduação Completa'), ('MI', 'Mestrado Incompleto'), ('MC', 'Mestrado Completo'), ('DI', 'Doutorado Incompleto'), ('DC', 'Doutorado Completo'), ('PDI', 'Pós-Doutorado Incompleto'), ('PDC', 'Pós-Doutorado Completo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_profile',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(default='', max_length=255),
        ),
    ]
