# Generated by Django 5.2 on 2025-05-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=1)),
                ('institution', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('education_level', models.CharField(choices=[('EM', 'Ensino Médio'), ('G', 'Graduação'), ('P', 'Pós-Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado'), ('PD', 'Pós-Doutorado')], max_length=2)),
                ('area_of_expertise', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
