# Generated by Django 5.2.2 on 2025-06-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_area_of_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_profile',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
