# Generated by Django 5.2 on 2025-05-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_profile',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
