# Generated by Django 5.2 on 2025-07-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
