# Generated by Django 5.2 on 2025-05-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_position_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
