# Generated by Django 5.2.1 on 2025-06-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
